services:
  - type: web
    name: neural-chat-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: neural-chat-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: serve -s frontend/dist -l 3000
    envVars:
      - key: NODE_VERSION
        value: 18
    buildFilter:
      paths:
        - frontend/**